server:
  port: 20009
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.40.255.238:2000/eureka/
  instance:
    prefer-ip-address: true
spring:
  profiles:
    active: dev
  redis:
    port: 6397
    host: 10.40.254.59
    pool:
      min-idle: 0
      max-idle: 8
      max-wait: -1
      max-active: 8
    timeout: 2000
  rabbitmq:
    host: 10.40.254.59
    port: 5672
    username: admin
    password: 123456
    listener:
          simple:
            default-requeue-rejected: false
            retry:
              max-attempts: 5
              enabled: true

  datasource:
    url: 'jdbc:mysql://10.40.254.59:4000/xgqoms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true'
    username: root
    password: 2018
    driver-class-name: 'com.mysql.jdbc.Driver'
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #最大连接数
      max-active: 100
      #最小连接数
      minIdle: 5
      #获取连接最小等待时间（毫秒）
      maxWait: 10000
      #解决Mysql 8小时断开空闲连接的问题
      validationQuery: SELECT 'x'
      time-between-eviction-runs-millis: 60000
  zipkin:
    base-url: http://10.40.255.238:9411
  sleuth:
    sampler:
      percentage: 1.0

#开启feign客户端路由
feign:
  hystrix:
    enabled: fasle

#设置断路器默认超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecondes: 10000

#日志处理/链路日志处理
logging:
  level:
    com.codingapi: info
    com.icecream.good.mapper: debug


#LCN相关配置
init-db: true
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  MaxAutoRetriesNextServer: 0

tm:
  manager:
    url: http://10.40.255.238:8899/tx/manager/

#设置mybatis mapper.xml扫描路径
mybatis:
  mapper-locations: classpath:mapper/*.xml




