server:
  port: 2002
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.40.253.210:2000/eureka/
  instance:
    prefer-ip-address: true
spring:
  profiles:
    active: dev
  rabbitmq:
    host: 10.40.254.59
    port: 5672
    username: admin
    password: 123456
  datasource:
    url: 'jdbc:mysql://10.40.254.59:4000/xgq?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true'
    username: root
    password: 2018
    driver-class-name: 'com.mysql.jdbc.Driver'
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #最大连接数
      max-active: 20
      #最小连接数
      minIdle: 5
      #获取连接最小等待时间（毫秒）
      maxWait: 10000
      #解决Mysql 8小时断开空闲连接的问题
      validationQuery: SELECT 'x'
      time-between-eviction-runs-millis: 60000
  zipkin:
    base-url: http://10.40.253.210:9411
  sleuth:
    sampler:
      percentage: 0.5

#开启feign客户端路由
feign:
  hystrix:
    enabled: true
#设置断路器默认超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecondes: 5000

#日志处理/链路日志处理
logging:
  level:
    com.codingapi: debug
    com.icecreamGroup.user.mapper: debug
    com.icecreamGroup.user.feignClients.OrderFeignClient: debug


#LCN相关配置
init-db: true
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  MaxAutoRetriesNextServer: 0

tm:
  manager:
    url: http://10.40.255.238:8899/tx/manager/

#配置【QQ/微信/微博】的appId与secret
login:
     QQappId: 1106041043
     QQsecret: jReqWlUw3105tGBZ
     WechatAppId: wxe0341da5922122cb
     WechatSecret: 97ccc6b8eb73638550137a2f74e5de94
     WeiboAppId: 1528767946
     WeiboSecret: 6ef467d04e49ac00b694e829a60fd0cc
     weibo-open-api-url: https://api.weibo.com/2/users/show.json



