#端口号
server:
  port: 2007

spring:
  profiles:
    active: dev
  application:
    name: comment-service
  datasource:
      url: 'jdbc:mysql://10.40.254.59:4000/xgqoms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true'
      username: root
      password: 2018
      driver-class-name: 'com.mysql.jdbc.Driver'
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        #最大连接数
        max-active: 100
        #最小连接数#
        minIdle: 5
        #获取连接最小等待时间（毫秒）
        maxWait: 10000
        #解决Mysql 8小时断开空闲连接的问题
        validationQuery: SELECT 'x'
        time-between-eviction-runs-millis: 60000
  #消息总线相关
  rabbitmq:
      host: 10.40.254.59
      port: 5672
      username: admin
      password: 123456
      listener:
        simple:
          #消费次数如果大于重试上限是否丢弃消息
          default-requeue-rejected: true
          retry:
            #重试次数
            max-attempts: 3
            #是否开启重试开关
            enabled: true
            #重试间隔
            initial-interval: 3000
  #链路追踪 http模式
  zipkin:
    base-url: http://10.40.253.210:9411/
  #链路追踪采样率
  sleuth:
    sampler:
      percentage: 1.0
  redis:
    timeout: 3000
    host: 10.40.254.59
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    database: 2
#eureka客户端相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.40.255.90:2000/eureka
  instance:
    #是否使用IP注册
    prefer-ip-address: true
    hostname: 10.40.255.90
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:${spring.application.name}

#LCN相关配置
init-db: true
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
  MaxAutoRetriesNextServer: 0
tm:
  manager.url: http://10.40.255.90:8899/tx/manager/

