#端口号
server:
  port: 2007

spring:
  profiles:
    active: dev
  application:
    name: comment-service
  #消息总线相关
  rabbitmq:
      host: 10.40.254.59
      port: 5672
      username: admin
      password: 123456
  #链路追踪 http模式
  zipkin:
    base-url: http://10.40.253.210:9411/
  #链路追踪采样率
  sleuth:
    sampler:
      percentage: 1.0
  redis:
    timeout: 3000
    host: 10.40.254.59
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    database: 2
#eureka客户端相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.40.255.238:2000/eureka
  instance:
    #是否使用IP注册
    prefer-ip-address: true
    hostname: 10.40.255.238
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}:${spring.application.name}

