server:
  port: 2007
spring:
  profiles:
    active: dev
  application:
    name: comment-service
  rabbitmq:
      host: 10.40.254.59
      port: 5672
      username: admin
      password: 123456
  zipkin:
    base-url: http://10.40.253.210:9411/
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.40.253.210:2000/eureka
  instance:
    prefer-ip-address: true

