server:
  port: 2007
spring:
  profiles:
    active: dev
  application:
    name: comment-service
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka

