server:
  port: 2001

spring:
  profiles:
    active: dev
  #模板引擎相关配置
  thymeleaf:
    cache: false
    encoding: 'UTF-8'
    mode: 'HTML5'
  datasource:
    url: 'jdbc:mysql://10.40.254.59:4000/xgqoms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&allowMultiQueries=true'
    username: root
    password: 2018
    driver-class-name: 'com.mysql.jdbc.Driver'
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #最大连接数
      max-active: 20
      #最小连接数#
      minIdle: 5
      #获取连接最小等待时间（毫秒）
      maxWait: 10000
      #解决Mysql 8小时断开空闲连接的问题
      validationQuery: SELECT 'x'
      time-between-eviction-runs-millis: 60000


  #消息总线相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


#  zipkin:
#    base-url: http://10.40.254.35:9411
  #链路追踪采样率，默认0.1 即10次请求只记录一次
  sleuth:
    sampler:
      percentage: 1.0

#  配置中心
#  cloud:
#    config:
#      uri: http://localhost:2005/
#      label: master
#      profile: dev


#mybatis mapper.xml文件扫描
mybatis:
  mapper-locations: 'classpath*:/Mapper/*.xml'

#Eureke 客户端注册服务相关配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka

#链路追踪相关配置
logging:
  level:
    root: info
    org.springframework.cloud.sleuth: Debug

#关闭security相关验证
management:
  security:
    enabled: false

feign:
  hystrix:
    enabled: true






