#默认的profile为dev,其他环境通过指定启动参数使用不同的profile
# 开发环境 java -jar order-service.0.0.1-SNAPSHOT.jar --spring.profiles.active=dev
# 测试环境 java -jar order-service.0.0.1-SNAPSHOT.jar --spring.profiles.active=test
# 生产环境 java -jar order-service.0.0.1-SNAPSHOT.jar --spring.profiles.active=prd
spring:
  application:
    name: order-service
#  profiles:
#    active: dev