server:
  port: 2000

eureka:
  instance:
    hostname: icecreamGroupEurekaServer
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://10.40.255.96:2000/eureka