server:
  port: 2000

eureka:
  instance:
    hostname: windows-peer2
    ip-address: 10.40.255.104
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://macOS-peer1:2000/eureka,http://os-x-peer1:2000/eureka,http://windows-peer1:2000/eureka
spring:
  application:
    name: ha-eureka
