server:
  port: 9411

spring:
  profiles:
    active: dev
  rabbitmq:
    port: 5672
    username: admin
    password: 123456
    host: 10.40.253.210
  sleuth:
    enabled: false
    sampler:
      percentage: 1.0
