server:
  port: 2004

#服务名称#
spring:
  application:
    name: zuul-server
  profiles:
    active: dev

#服务中心默认地址#
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.40.253.210:2000/eureka/

#配置zuul网关#
zuul:
  routes:
    order-api:
      path: /order-api/**
      serviceId: order-service
    user-api:
      path: /user-api/**
      serviceId: user-service
    comment-api:
      path: /comment-api/**
      serviceId: comment-service

#设置断路器默认超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#ribbon:
#  eureka:
#    enabled: false
#
#order-api:
#  ribbon:
#    listOfServers: localhost,localhost