#服务名称#
spring:
  application:
    name: zuul-server
  profiles:
    active: dev

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecondes: 10000


#服务中心默认地址#
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.40.255.238:2000/eureka/

#配置zuul网关#
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    order-api:
      path: /order-api/**
      serviceId: order-service
    user-api:
      path: /user-api/**
      serviceId: user-service
    comment-api:
      path: /comment-api/**
      serviceId: comment-service
    good-api:
      path: /good-api/**
      serviceId: good-service


#设置断路器默认超时时间

#ribbon:
#  eureka:
#    enabled: false
#
#order-api:
#  ribbon:
#    listOfServers: localhost,localhost